services:
  - type: web
    name: codeswayam-core-api
    env: node
    region: ohio
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this in the Render dashboard
      - key: JWT_SECRET
        sync: false # Set this in the Render dashboard
